[package]
name = "learning"
version = "0.1.0"
authors = ["sdn0303 <sdn0303.guitar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
